use rand::Rng;

const FORTUNES: &[&str] = &[
    "A beautiful, smart, and loving person will be coming into your life.",
    "A dubious friend may be an enemy in camouflage.",
    "A faithful friend is a strong defense.",
    "A fresh start will put you on your way.",
    "A golden egg of opportunity falls into your lap this month.",
    "A good time to finish up old tasks.",
    "A lifetime of happiness lies ahead of you.",
    "A light heart carries you through all the hard times.",
    "A smooth long journey! Great expectations.",
    "All your hard work will soon pay off.",
    "An important person will offer you support.",
    "Believe it can be done.",
    "Curiosity kills boredom. Nothing can kill curiosity.",
    "Determine what you want and go for it.",
    "Do not make extra work for yourself.",
    "Don't just spend time, invest it.",
    "Every flower blooms in its own time.",
    "Fortune favors the brave.",
    "Go take a rest; you deserve it.",
    "Good news will come to you by mail.",
    "Happiness begins with facing life with a smile and a wink.",
    "If you feel you are right, stand firmly by your convictions.",
    "Keep your eyes open. You never know what you might see.",
    "Love is on its way.",
    "Nature, time and patience are the three great physicians.",
    "Now is the time to try something new.",
    "Others can help you now.",
    "Practice makes perfect.",
    "Smile when picking up the phone. The caller will hear it in your voice.",
    "Success lies in the hands of those who want it.",
    "The early bird gets the worm, but the second mouse gets the cheese.",
    "The greatest risk is not taking one.",
    "The one that is beautiful is not always good, but the one that is good is always beautiful.",
    "The wise man is the one who makes you think he is dumb.",
    "Things may seem dark, but the sun is about to shine.",
    "Today is a good day for a new beginning.",
    "You are never selfish to those who share your dreams.",
    "You can make your own happiness.",
    "You will be successful in your work.",
    "You will find a thing. It may be important.",
    "Your hard work is about to pay off. Enjoy!",
    "Your talents will be recognized and suitably rewarded.",
    "21 million, no more.",
    "In a world of fiat, be bitcoin.",
    "The best time to stack sats was yesterday. The second best time is now.",
    "Not your keys, not your coins.",
    "Lightning is the path to abundance.",
    "Patience and HODL go hand in hand.",
    "Proof of work beats proof of trust.",
    "The cypherpunk writes code.",
];

pub fn random_fortune() -> &'static str {
    let mut rng = rand::rng();
    FORTUNES[rng.random_range(0..FORTUNES.len())]
}
